# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks

  - repo: https://codeberg.org/frnmst/md-toc
    rev: "8.1.4"
    hooks:
      - id: md-toc
        args: [-p, "cmark", "-l6"]

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.32.2
  #   hooks:
  #     - id: markdownlint-fix

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.6.1" # pick a git hash / tag to point to
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude_types:
          - 'text'
      - id: end-of-file-fixer
        exclude_types:
          - 'text'
      - id: check-yaml
      - id: check-added-large-files
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
